#!/usr/bin/env python3
"""
generate_camera_ready_tables.py — rebuild the camera-ready paper tables.

Regenerates the CSV and LaTeX forms of the three tables reported in the
camera-ready paper:

    table1_main          pooled CV / ES / VM-F1 / RMEM, plus per-model VM-F1
    table_robustness     strict/tolerant RMEM deltas with CIs for the two key
                         transitions, plus per-model McNemar for Hybrid vs DKB
    table3_categories    DKB+Hybrid VM-F1 by category x model

This script does **no** LLM generation and does **not** touch the graph. It only
reads files that already exist and reshapes them.

Inputs, and where each comes from
---------------------------------
HISTORICAL (immutable, produced by the reported June 2026 run):

    ../05_results/raw/results_full.jsonl
        3,750 raw generation records. Read only to recompute pooled CV and ES,
        and to cross-check VM-F1 against the derived files. Its `metrics.SE`
        field is VM-F1 under its legacy name (see METRICS.md). Never rewritten.

CAMERA-READY DERIVED (produced by re-executing the stored queries against
JPM2KG; see camera_ready_evaluator.py):

    ../05_results/camera_ready/main_results/pooled_by_configuration.csv
    ../05_results/camera_ready/main_results/vmf1_by_model_and_configuration.csv
    ../05_results/camera_ready/main_results/by_model_and_configuration.csv
    ../05_results/camera_ready/category_results/vmf1_by_category_model_dkbhybrid.csv
    ../05_results/camera_ready/robustness/rmem_strict_vs_tolerant_by_model.csv
    ../05_results/camera_ready/statistics/exact_paired_tests_rmem.csv
    ../05_results/camera_ready/statistics/cluster_bootstrap_rmem.csv

Output
------
    ../05_results/tables/            (override with --out)

Usage
-----
    python3 generate_camera_ready_tables.py
    python3 generate_camera_ready_tables.py --out /tmp/tables --check
"""

from __future__ import annotations

import argparse
import csv
import json
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent
CR = PKG / "05_results" / "camera_ready"
RAW = PKG / "05_results" / "raw" / "results_full.jsonl"

# Display order and paper labels for the six prompting configurations.
CONFIG_ORDER = [
    ("Baseline", "Baseline"),
    ("Schema Baseline", "Schema"),
    ("Schema+Values", "Schema+Values"),
    ("DKB-NoExamples", "DKB-NoExamples"),
    ("DKB", "DKB"),
    ("DKB+Hybrid", "DKB+Hybrid"),
]
MODEL_ORDER = ["llama3.2:3b", "gemma2:9b", "qwen2.5-coder:32b", "qwen2.5:72b"]
MODEL_SHORT = {"llama3.2:3b": "L3B", "gemma2:9b": "G9B",
               "qwen2.5-coder:32b": "QC32B", "qwen2.5:72b": "Q72B"}
CATEGORY_ORDER = ["Aggregate", "Temporal", "Health Risk",
                  "Station Filtering", "Comparative"]

# Maps the raw JSONL's system keys onto the paper's configuration labels.
SYSTEM_TO_CONFIG = {
    "baseline": "Baseline",
    "cypherbench_style": "Schema Baseline",
    "schema_plus_values": "Schema+Values",
    "dkb_no_examples": "DKB-NoExamples",
    "dkb": "DKB",
    "dkb_hybrid": "DKB+Hybrid",
}


def read_csv(path: Path) -> list[dict]:
    with path.open() as f:
        return list(csv.DictReader(f))


def f3(x) -> str:
    """
    Three decimals, leading zero stripped, as the paper prints them.

    Rounds half-UP rather than using Python's default half-to-even, so that a
    stored 0.5545 prints as .555 and matches the paper.
    """
    if x is None or x == "":
        return "--"
    s = str(Decimal(str(x)).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP))
    return s[1:] if s.startswith("0.") else s


def write_csv(path: Path, header: list[str], rows: list[list]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    print(f"  wrote {path.relative_to(PKG)}")


def write_tex(path: Path, caption: str, label: str,
              colspec: str, header: list[str], rows: list[list]) -> None:
    lines = [
        "% Generated by 04_pipeline/generate_camera_ready_tables.py -- do not edit by hand.",
        "\\begin{table}[t]", "\\centering", f"\\caption{{{caption}}}",
        f"\\label{{{label}}}", f"\\begin{{tabular}}{{{colspec}}}", "\\hline",
        " & ".join(header) + " \\\\", "\\hline",
    ]
    lines += [" & ".join(str(c) for c in r) + " \\\\" for r in rows]
    lines += ["\\hline", "\\end{tabular}", "\\end{table}"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    print(f"  wrote {path.relative_to(PKG)}")


# ── CV / ES straight from the immutable raw generations ──────────────────────

def pooled_cv_es_from_raw() -> dict[str, dict[str, float]]:
    """Pooled CV and ES per configuration, computed from results_full.jsonl."""
    acc: dict[str, list[list[float]]] = {}
    with RAW.open() as f:
        for line in f:
            if not line.strip():
                continue
            rec = json.loads(line)
            cfg = SYSTEM_TO_CONFIG.get(rec["system"])
            if cfg is None:      # the fine-tuned baseline, reported separately
                continue
            m = rec["metrics"]
            bucket = acc.setdefault(cfg, [[], []])
            bucket[0].append(float(m["CV"]))
            bucket[1].append(float(m["ES"]))
    return {cfg: {"CV": sum(cv) / len(cv), "ES": sum(es) / len(es), "n": len(cv)}
            for cfg, (cv, es) in acc.items()}


# ── Table 1: main results ────────────────────────────────────────────────────

def table1_main(out: Path) -> None:
    print("Table 1 (main results)")
    pooled = {r["prompting_configuration"]: r
              for r in read_csv(CR / "main_results/pooled_by_configuration.csv")}
    vmf1 = {r["prompting_configuration"]: r
            for r in read_csv(CR / "main_results/vmf1_by_model_and_configuration.csv")}
    per_model = {}
    for r in read_csv(CR / "main_results/by_model_and_configuration.csv"):
        per_model[(r["prompting_configuration"], r["model"])] = r
    cv_es = pooled_cv_es_from_raw()

    # (a) pooled CV / ES / VM-F1 / RMEM
    rows_a = []
    for key, label in CONFIG_ORDER:
        p, c = pooled[key], cv_es[key]
        rows_a.append([label, f3(c["CV"]), f3(c["ES"]),
                       f3(p["vmf1_saved"]), f3(p["rmem_strict_accuracy"])])
    ft = pooled.get("Text2Cypher-FT")
    write_csv(out / "table1_main.csv",
              ["System", "CV", "ES", "VM-F1", "RMEM"], rows_a)
    write_tex(out / "table1_main.tex",
              "Pooled performance across four LLMs ($N=600$ per configuration). "
              "VM-F1 is Value-Multiset F1; RMEM is Row-Multiset Exact Match.",
              "tab:main_results", "lrrrr",
              ["System", "CV", "ES", "VM-F1", "RMEM"], rows_a)

    # (b) per-model VM-F1
    rows_b = []
    for key, label in CONFIG_ORDER:
        r = vmf1[key]
        rows_b.append([label] + [f3(r[m]) for m in MODEL_ORDER])
    write_csv(out / "table2_per_llm.csv",
              ["System"] + [MODEL_SHORT[m] for m in MODEL_ORDER], rows_b)
    write_tex(out / "table2_per_llm.tex",
              "VM-F1 by model ($N=150$ per cell). L3B: Llama-3.2-3B; "
              "G9B: Gemma-2-9B; QC32B: Qwen2.5-Coder-32B; Q72B: Qwen2.5-72B.",
              "tab:per_llm", "lrrrr",
              ["System"] + [MODEL_SHORT[m] for m in MODEL_ORDER], rows_b)

    # per-model RMEM, alongside (a) and (b) but not a paper table of its own
    rows_c = []
    for key, label in CONFIG_ORDER:
        rows_c.append([label] + [
            f3(per_model[(key, m)]["rmem_strict_accuracy"]) for m in MODEL_ORDER])
    write_csv(out / "table2_per_llm_rmem.csv",
              ["System"] + [MODEL_SHORT[m] for m in MODEL_ORDER], rows_c)

    if ft:
        c = ft
        write_csv(out / "table1_finetuned_baseline.csv",
                  ["System", "N", "VM-F1", "RMEM"],
                  [["Text2Cypher-FT", c["n"], f3(c["vmf1_saved"]),
                    f3(c["rmem_strict_accuracy"])]])


# ── Table: robustness and statistics ─────────────────────────────────────────

TRANSITIONS = [
    ("DKB-NoExamples vs Schema+Values", "Schema+Values -> DKB-NoExamples"),
    ("DKB+Hybrid vs DKB", "DKB -> DKB+Hybrid"),
]


def table_robustness(out: Path) -> None:
    print("Table 2 (robustness / statistics)")
    tol = {(r["prompting_configuration"], r["model"]): r
           for r in read_csv(CR / "robustness/rmem_strict_vs_tolerant_by_model.csv")}
    boot = {(r["metric"], r["comparison"]): r
            for r in read_csv(CR / "statistics/cluster_bootstrap_rmem.csv")}
    tests = read_csv(CR / "statistics/exact_paired_tests_rmem.csv")

    def pooled_acc(cfg: str, col: str) -> float:
        vals = [tol[(cfg, m)] for m in MODEL_ORDER]
        n = sum(int(v["n"]) for v in vals)
        return sum(float(v[col]) * int(v["n"]) for v in vals) / n

    # (a) key transitions: strict and tolerant RMEM deltas with clustered CIs
    rows = []
    for comparison, label in TRANSITIONS:
        treat, comp = [s.strip() for s in comparison.split(" vs ")]
        for metric, col in (("RMEM_strict", "rmem_strict_accuracy"),
                            ("RMEM_tolerant", "rmem_tolerant_accuracy")):
            b = boot[(metric, comparison)]
            rows.append([
                label,
                "strict" if metric.endswith("strict") else "tolerant",
                f3(pooled_acc(comp, col)), f3(pooled_acc(treat, col)),
                f"{float(b['macro_mean_diff']):+.4f}",
                f"[{float(b['ci95_lo']):+.4f}, {float(b['ci95_hi']):+.4f}]",
            ])
    write_csv(out / "table_robustness.csv",
              ["transition", "evaluation", "rmem_from", "rmem_to",
               "delta", "ci95"], rows)
    write_tex(out / "table_robustness.tex",
              "Validity-filter robustness. Strict and tolerant RMEM for the two key "
              "grounding transitions, with query-cluster bootstrap 95\\% CIs "
              "(10,000 resamples).",
              "tab:robustness", "llrrrr",
              ["Transition", "Eval.", "From", "To", "$\\Delta$", "95\\% CI"], rows)

    # (b) per-model exact McNemar, DKB+Hybrid vs DKB, strict RMEM
    rows_m = []
    for t in tests:
        if (t["metric"] == "RMEM_strict"
                and t["comparison"] == "DKB+Hybrid vs DKB"
                and t["model"] in MODEL_ORDER):
            rows_m.append([
                MODEL_SHORT[t["model"]],
                t["both_correct"], t["treatment_only_correct"],
                t["comparator_only_correct"],
                f"{float(t['accuracy_difference']):+.4f}",
                t["p_display_two_sided"],
            ])
    rows_m.sort(key=lambda r: [MODEL_SHORT[m] for m in MODEL_ORDER].index(r[0]))
    b = boot[("RMEM_strict", "DKB+Hybrid vs DKB")]
    write_csv(out / "table_mcnemar_hybrid_vs_dkb.csv",
              ["model", "both_correct", "hybrid_only", "dkb_only",
               "delta_rmem", "exact_p_two_sided"], rows_m)
    write_tex(out / "table_mcnemar_hybrid_vs_dkb.tex",
              "DKB+Hybrid vs DKB, strict RMEM. Exact McNemar per model; the four "
              "$p$-values are reported separately and are not combined. "
              "Cross-model clustered effect: "
              f"${float(b['macro_mean_diff']):+.4f}$, 95\\% CI "
              f"$[{float(b['ci95_lo']):+.4f}, {float(b['ci95_hi']):+.4f}]$.",
              "tab:mcnemar", "lrrrrr",
              ["Model", "Both", "Hybrid only", "DKB only",
               "$\\Delta$", "exact $p$"], rows_m)


# ── Table 3: categories ──────────────────────────────────────────────────────

def table3_categories(out: Path) -> None:
    print("Table 3 (categories)")
    rows_in = read_csv(CR / "category_results/vmf1_by_category_model_dkbhybrid.csv")
    by_model = {r["model"]: r for r in rows_in}
    pooled_key = next(k for k in by_model if k.startswith("POOLED"))

    rows = []
    for cat in CATEGORY_ORDER:
        rows.append([cat] + [f3(by_model[m][cat]) for m in MODEL_ORDER]
                    + [f3(by_model[pooled_key][cat])])
    rows.append(["Overall"] + [f3(by_model[m]["overall"]) for m in MODEL_ORDER]
                + [f3(by_model[pooled_key]["overall"])])

    header = ["Category"] + [MODEL_SHORT[m] for m in MODEL_ORDER] + ["Pooled"]
    write_csv(out / "table3_categories.csv", header, rows)
    write_tex(out / "table3_categories.tex",
              "DKB+Hybrid VM-F1 by benchmark category and model.",
              "tab:categories", "lrrrrr", header, rows)


# ── Consistency check against the published paper values ─────────────────────

PAPER_MAIN = {
    "Baseline":       (".010", ".652", ".000", ".000"),
    "Schema":         (".565", ".508", ".001", ".000"),
    "Schema+Values":  (".718", ".495", ".070", ".035"),
    "DKB-NoExamples": (".800", ".697", ".215", ".075"),
    "DKB":            (".757", ".670", ".328", ".077"),
    "DKB+Hybrid":     (".820", ".725", ".416", ".152"),
}
PAPER_PER_MODEL = {
    "Baseline":       (".000", ".000", ".000", ".000"),
    "Schema":         (".000", ".000", ".004", ".000"),
    "Schema+Values":  (".017", ".072", ".094", ".099"),
    "DKB-NoExamples": (".027", ".061", ".495", ".277"),
    "DKB":            (".015", ".244", ".462", ".593"),
    "DKB+Hybrid":     (".126", ".279", ".647", ".614"),
}
PAPER_CATEGORIES = {
    "Aggregate":         (".327", ".487", ".712", ".792", ".580"),
    "Temporal":          (".009", ".197", ".773", ".693", ".418"),
    "Health Risk":       (".000", ".167", ".800", ".700", ".417"),
    "Station Filtering": (".205", ".412", ".351", ".380", ".337"),
    "Comparative":       (".000", ".000", ".555", ".397", ".238"),
    "Overall":           (".126", ".279", ".647", ".614", ".416"),
}


def check(out: Path) -> int:
    """Compare the generated tables against the values printed in the paper."""
    print("Consistency check against camera-ready paper values")
    bad = 0

    def cmp(name, got, want):
        nonlocal bad
        if tuple(got) != tuple(want):
            bad += 1
            print(f"  MISMATCH {name}: generated {tuple(got)} != paper {tuple(want)}")

    for r in read_csv(out / "table1_main.csv"):
        cmp(f"main/{r['System']}",
            (r["CV"], r["ES"], r["VM-F1"], r["RMEM"]), PAPER_MAIN[r["System"]])
    for r in read_csv(out / "table2_per_llm.csv"):
        cmp(f"per-model/{r['System']}",
            (r["L3B"], r["G9B"], r["QC32B"], r["Q72B"]),
            PAPER_PER_MODEL[r["System"]])
    for r in read_csv(out / "table3_categories.csv"):
        cmp(f"category/{r['Category']}",
            (r["L3B"], r["G9B"], r["QC32B"], r["Q72B"], r["Pooled"]),
            PAPER_CATEGORIES[r["Category"]])

    print("  OK — all generated values match the paper." if bad == 0
          else f"  {bad} mismatch(es)")
    return bad


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=PKG / "05_results" / "tables")
    ap.add_argument("--check", action="store_true",
                    help="verify the generated tables against the paper's values")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    table1_main(args.out)
    table_robustness(args.out)
    table3_categories(args.out)
    return check(args.out) if args.check else 0


if __name__ == "__main__":
    raise SystemExit(main())
